### ISSUE TITLE
Not working on 1.19.2

### ISSUE THREAD

**Issue by alexhulbert** [StackDoubleFlow/MCWaylandFix#2]
Hi, I've been having issues with the other patched glfw libraries, so I figured I'd give this mod a shot. When I run [Admicos/minecraft-wayland#56](https://github.com/Admicos/minecraft-wayland/pull/56) or [BoyOrigin/glfw-wayland](https://github.com/BoyOrigin/glfw-wayland), it sometimes works fine, but then other times, no matter how much I reboot, recreate myt profile, etc, the window doesn't get created. I still hear the background noise of the window, so it seems like there's some sort of context drawing issue. Disabling nvidia or wayland-glfw fixes the issue, so it might have some relation to nvidia as well.

I figured this might be a better solution, but it doesn't seem to work with 1.19.2+forge. When I run it with the latest version of glfw from my package manager (some variant of 3.4), I get an error complaining that minecraft can't set the icon. I compiled commit 3eaf125 of glfw with only the patch that disables that warning (not the other patches that are usually included with glfw) and tried running that with the mod in this repo as well. That got me past the error, but the window itself didn't actually open with wayland.

Do you have any ideas about how I might go about troubleshooting this issue? Perhaps some function I can add some printlns into to get a little more insight into why the window isn't appearing?

Thanks!

**Comment by StackDoubleFlow** [comment]
Hey, I haven't tried this mod on Nvidia yet since explicit sync on Sway is still unusable. Looking at `glfw-wayland` repository, it does require `__GL_THREADED_OPTIMIZATIONS=0`, so confirm that you're using that env var. Also, you can try using `WAYLAND_DEBUG` to inspect the wayland protocol communication. Double check that the surface is actually getting committed to, otherwise your window won't show up.

The sole purpose of this mod is to prevent Minecraft from trying to set the window icon, but you say you're running forge? This is a fabric mod so if that's true that may be the reason it doesn't work. 

Let me know if that is the case, thanks.

**Comment by alexhulbert** [comment]
Thanks for helping! I'm setting that env var. Good call on the WAYLAND_DEBUG, I'm definitely seeing something funky. I'm seeing thousands of

```
{Default Queue}  -> wl_surface#35.attach(nil, 0, 0)
{Default Queue}  -> wl_surface#35.damage(0, 0, 854, 480)
{Default Queue}  -> wl_surface#35.commit()
 -> wl_display#1.sync(new id wl_callback#57)
{Display Queue} wl_display#1.delete_id(57)
wl_callback#57.done(35290)
```

per second. Everything is identical in the repeated messages except the number in wl_callback#57.done, which seems to increase every 2-3 seconds. 

When nvidia is disabled, I get the following repeated message instead:

```
[2254004.164] {mesa egl surface queue}  -> wl_surface#35.attach(wl_buffer#29, 0, 0)
[2254004.169] {mesa egl surface queue}  -> wl_surface#35.damage(0, 0, 2147483647, 2147483647)
[2254004.171] {mesa egl surface queue}  -> wl_surface#35.commit()
[2254004.172] {mesa egl surface queue}  -> wl_display#1.sync(new id wl_callback#52)
[2254004.370] {Display Queue} wl_display#1.delete_id(52)
[2254019.887] {mesa egl surface queue} wl_buffer#46.release()
[2254019.904] {mesa egl surface queue} wl_callback#52.done(41803)
```

Looks like the nil buffer is the issue, so I'm going to try and figure out why its nil unless you have any better ideas.

**Comment by StackDoubleFlow** [comment]
That is odd. It may possibly be a bug in glfw itself then, but honestly it's way outside of my expertise. Did you figure it out?

**Comment by alexhulbert** [comment]
i'm going to go ahead and close this. i made another issue elsewhere that's more visible and im fine running it in x11 even though its slower. itll probably fix itself at some point.
